language: viml

install:
  - hg clone https://code.google.com/p/vim/ /tmp/vim
  - (cd /tmp/vim && ./configure && make && sudo make install)
  - git clone https://github.com/thinca/vim-themis /tmp/themis
  - git clone https://github.com/syngan/vim-vimlint /tmp/vimlint
  - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vimlparser
  - sudo pip install vim-vint

script:
  - vim --cmd version --cmd quit

  - /tmp/themis/bin/themis --reporter spec

  - vint --version
  - vint plugin/ autoload/

  - sh /tmp/vimlint/bin/vimlint.sh -l /tmp/vimlint -p /tmp/vimlparser -e EVL103=1 -e EVL102.l:_=1 .
